name: GitHub-Profile-3D-Contrib

on:
  schedule:
    # Run at 0 am every day
    - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_ACTION }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          if git commit -m "generated"; then
            git push
          fi
      - name: OpenCommit — improve commits with AI
        uses: di-sukharev/opencommit@github-action-v1.0.2
